### PR TITLE
add .Net Standard 2.0 project

### PR DESCRIPTION
**Pull request by neilboyd**
I find this library useful but I want to use it in a .Net Standard 2.0 project so I created this version

### CODE REVIEW

**Comment by dkackman** [comment]
Hi @neilboyd - I had added a netstandard1.1 project a long time ago but for some reason never added it to the nuget package. 1.1 should be compatible with a netstandard 2.0 project.

Please try this release and let me know if it works for you: https://github.com/dkackman/LinqStatistics/releases/tag/v2.2.1

**Comment by neilboyd** [comment]
I tried the 1.1 project before I created the 2.0 one.
I get this error:
image

**Comment by dkackman** [comment]
I was able to add a reference to the 1.1 lib from a 2.0 dll project using the nuget package in the release. Can you give that a shot for me? (the nupkg is in the zip associated with the release).

If it works i'll push it to nuget.

**Comment by neilboyd** [comment]
Okay, but that won't be until after the weekend

**Comment by neilboyd** [comment]
Yes, it works!

**Comment by dkackman** [comment]
Cool. No idea why i didn't add that to the nuget package when i added the project. I'll push the package sometime this week.

**Comment by dkackman** [comment]
Published. 
https://www.nuget.org/packages/LinqStatistics/2.2.1

**Pull request closed without merging**
